package.json

chore: make scripts package manager independent

---

README.md
package.json
pnpm-lock.yaml
src/builder.ts
src/wallet-data.ts

Generate wallets **Mnemonic**, **Address** and **Public Key**:

feat: generate custom wallet

---

config/config.js

Set default API server for easier onboarding

chore: set testnet default API server

---

src/builder.ts
src/index.ts
src/wallet-data.ts

feat: generate BLS keys

---

README.md

Adds additional troubleshooting to the readme

chore: add python path requirement

---

src/builder.ts

Adds the vendor field to multi payments.

fix: add vendor field to multi payment

---

src/client.ts

Add a fallback to the nonce lookup to support the changed response format while remaining backward compatible.
Also see: https://github.com/ArkEcosystem/mainsail/pull/485

fix: wallet nonce lookup

---

src/builder.ts
src/client.ts

Updates the transaction builder to get the nonce by wallet address since is currently not working

fix: update to get wallet nonce by address

---

config/config.js

fix: update default vote asset

---

config/config.js
src/builder.ts
src/index.ts

adds multisignature registration as option

feat: multisignature registration support

---

README.md
config/config.js
package.json
src/validator-data.ts

Adds a separate `yarn validator` command to only generate public/private keypair to be used for a validator registration to quickly generate one when needed.

feat: validator key generator

---

src/builder.ts
src/index.ts

feat: support contract calls with arguments from cli 

---

config/config.js
package.json
pnpm-lock.yaml

refactor: use evm network endpoints and configuration

---

config/config.js
src/builder.ts

refactor: evm testnet defaults

---

src/builder.ts

fix: nonce check for missing address

---

config/config.js
package.json
src/builder.ts
src/message-sign.ts
src/message-verify.ts
src/message.ts

related to https://app.clickup.com/t/86du3ct7y
todo:
- ~~add a verify option as well as signing~~

feat: message signing/verifying

---

config/config.js
src/builder.ts

- allows resigning a validator by calling the right method
- adds unvote support

fix: resign validator and unvote

---

config/config.js
config/contracts/revert.js
scripts/reverted-contract-call.js

```shell
node scripts/reverted-contract-call.js
```

feat: add script to perform invalid contract call

---

scripts/multi-tx.js

feat: add script for sending multiple transactions

---

src/builder.ts

fix: take default network in tx builder

---

config/contracts/multipayment.js

https://app.clickup.com/t/86dw15cmu

chore: update multipayment contract address

---

config/config.js
package.json
pnpm-lock.yaml
src/actions/generate-fixtures.ts
src/actions/message-sign.ts
src/actions/message-verify.ts

https://app.clickup.com/t/86dw832k3

refactor: message signing

---

config/fixtures.js

The validator registration fixture should have a value assigned to it

chore: add value to validator registration fixture

---

package.json
pnpm-lock.yaml
src/actions/generate-fixtures.ts

Update to sign message using eip191 to be aligned with https://github.com/ArdentHQ/typescript-crypto/pull/59
Related task https://app.clickup.com/t/86dwq94f5

refactor: sign message using eip191

---

src/builder.ts
src/index.ts

feat: normalize contract args
